FROM python:3.8.13
WORKDIR /app

# TODO - add all the necessary to run the script populate_db.py in this image
# 1. Copy the requirements.txt file to the image
# 2. Install the dependencies
# 3. Copy the content of the current directory to the image
# 4. Run the populate_db.py script

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ./ /app

CMD ["python", "populate_db.py"]
